spring.application.name=SpringBoot

spring.datasource.url=jdbc:postgresql://localhost:5432/db_name
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_cotextual_creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=votre@email.com
spring.mail.password=votre_mot_de_passe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

logging.file.name=app.log
