spring.application.name=SpringBoot

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_cotextual_creation=true

file.upload-dir = ./src/main/resources/static/images/
spring.resources.static-locations=D:/L3/ProjetSpring/images/

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=eliasvano78@gmail.com
spring.mail.password=vwlunnelrmshyedx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

logging.file.name=app.log